version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg15
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
      image: redis:latest
      ports:
        - "6379:6379"
      environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - REDIS_DB=0
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8989
    volumes:
      - .:/usr/src/app
    ports:
      - "8989:8989"
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=db
      - CELERY_REDIS_HOST=redis
    depends_on:
      - db
      - redis
  celery_worker:
    build: .
    command: celery -A core worker -P gevent -c 1000 --loglevel=info
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=db
      - CELERY_REDIS_HOST=redis
    volumes:
      - .:/usr/src/app
  celery_beat:
    build: .
    command: celery -A core beat --loglevel=info
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=db
      - CELERY_REDIS_HOST=redis
    volumes:
      - .:/usr/src/app
