# Generated by Django 4.2.9 on 2024-04-03 03:04

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("credentials", models.JSONField(default=dict)),
                ("token", models.JSONField(default=dict)),
                ("email", models.CharField(max_length=1000)),
            ],
            options={
                "verbose_name": "Config",
                "verbose_name_plural": "Configs",
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("doc_id", models.CharField(db_index=True, max_length=1000)),
                ("excluded_embed_metadata_keys", models.JSONField(default=list)),
                ("excluded_llm_metadata_keys", models.JSONField(default=list)),
                ("extra_info", models.JSONField(default=dict)),
                ("hash", models.CharField(max_length=1000)),
                ("metadata", models.JSONField(default=dict)),
                ("metadata_template", models.TextField()),
                ("text", models.TextField()),
                ("text_template", models.TextField()),
                ("source_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_modified_at", models.DateTimeField(blank=True, null=True)),
                ("chunk_size", models.IntegerField(default=1000)),
                ("chunk_overlap", models.IntegerField(default=20)),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("folder_id", models.CharField(max_length=1000)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("cron_config", models.JSONField(blank=True, default=dict, null=True)),
                ("sync_interval", models.IntegerField(default=5)),
                ("config", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="datastore.config")),
            ],
            options={
                "verbose_name": "Folder",
                "verbose_name_plural": "Folders",
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("chunk", models.TextField()),
                ("embedding", pgvector.django.VectorField(dimensions=384, null=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="datastore.document"
                    ),
                ),
            ],
            options={
                "verbose_name": "Document Chunk",
                "verbose_name_plural": "Document Chunks",
            },
        ),
        migrations.AddField(
            model_name="document",
            name="folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="documents", to="datastore.folder"
            ),
        ),
    ]
