# Generated by Django 4.2.9 on 2024-02-25 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("datastore", "0002_folder_cron_config_folder_last_sync_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="source_created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="document",
            name="source_modified_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="document",
            name="doc_id",
            field=models.CharField(db_index=True, max_length=1000),
        ),
    ]
