# Generated by Django 4.2.9 on 2024-02-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datastore", "0003_document_source_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="source_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="document",
            name="source_modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
