# Generated by Django 4.2.9 on 2024-02-29 05:21

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("datastore", "0004_alter_document_source_created_at_and_more"),
    ]

    operations = [VectorExtension()]
