# Generated by Django 4.2.9 on 2024-03-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datastore", "0007_alter_documentchunk_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="folder",
            name="sync_interval",
            field=models.IntegerField(default=5),
        ),
    ]
