# Generated by Django 4.2.9 on 2024-03-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datastore", "0008_folder_sync_interval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folder",
            name="cron_config",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
